#!/bin/bash
code --install-extension 13xforever.language-x86-64-assembly
code --install-extension christian-kohler.path-intellisense
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-diff
code --install-extension foxundermoon.shell-format
code --install-extension hbenl.vscode-test-explorer
code --install-extension humao.rest-client
code --install-extension James-Yu.latex-workshop
code --install-extension jebbs.plantuml
code --install-extension joffreykern.markdown-toc
code --install-extension maddouri.cmake-tools-helper
code --install-extension matepek.vscode-catch2-test-adapter
code --install-extension mine.cpplint
code --install-extension ms-azuretools.vscode-docker
code --install-extension MS-CEINTL.vscode-language-pack-ja
code --install-extension ms-python.python
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode-remote.remote-ssh-explorer
code --install-extension ms-vscode-remote.vscode-remote-extensionpack
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension p1c2u.docker-compose
code --install-extension PKief.material-icon-theme
code --install-extension Rubymaniac.vscode-direnv
code --install-extension twxs.cmake
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.material-theme
